extends Node2D

## Scene orchestrator: draws the baked ground, then places every prop/entity
## from the active level's ASCII map as a live Y-sorted node (data in PropTable,
## generated by tools/gen_prop_table.py to mirror the preview renderer's pass 3).
##
## The active level comes from LevelRegistry (keyed by Game.current_level_id):
## its below-player look (terrain + procedural detail + any bridge floor) is a
## single pre-baked image; the Level TileMapLayer is kept ONLY for collision
## (water/wall blocks; walkable tiles free) and rendered transparent — its
## visuals are superseded by the baked image.

const DIALOGUE_BOX_SCENE := preload("res://scenes/dialogue_box.tscn")

## The windmill's rotating cross (map audit M7), shipped separately from the
## tower in the pack. (Villager variety moved to modular VillagerNpc nodes —
## the old premade-sheet alt, M10, is retired.)
const WINDMILL_SAILS := (
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy"
	+ "/Buildings/Buildings/Unique_Buildings/Windmill/Windmill_Sail_Anim.png"
)

## Symbols handled outside PropTable: terrain (painted + baked), fences (F needs
## neighbour-aware pieces), spawn, and node anchors ("$" = Ariana, spawned as a
## live critter node below — NOT a table prop, else a static duck stacks on her).
## Used by the build-time coverage assert so a future map edit can never silently
## reintroduce the old blank-grass gap.
const TERRAIN_SYMS := [
	".", "#", "S", "~", "B", "D", "Q", "c", "g", "O", "k", "a", "l", "@", "$", "_", "X", ">", "!"
]
const FENCE_SYMS := ["F", "|"]

## Where Evan stands relative to his stall's cell center (front-left, clear of
## the stall collider).
const EVAN_OFFSET := Vector2(-20.0, 10.0)

## The onboarding guide's cell — grass just east of the village spawn "S" (6,25),
## in view when the intro pan lands on the player. Valley-only (gated with Ariana).
const GUIDE_CELL := Vector2i(9, 25)

## Ambient-animal animation, keyed by map symbol (from the audited sheet layout —
## 32px frames unless "frame_size" says otherwise). "idle"/"idle_n" = the idle
## row + frame count; the optional "walk"/"walk_n" + "wander" enable a slow
## random stroll for land animals with a walk cycle. Water animals (a/l swimming,
## k/@ capybara) bob in place only. hframes/vframes derive per sheet at spawn.
## Two sheet quirks (both playtest-caught): the chicken "C" is 2x2 = 4 frames
## total (row 0 idle, row 1 walk — a 6-frame walk overran it every step), and
## the butterfly "y" is 8px frames, 2 flaps x 8 color rows — frame_size 16 drew
## a 2x2 block of FOUR butterflies as one sprite; the color row is randomized
## per instance in ambient_animal.gd.
##
## "foot" (px) shifts the node origin so the animal's VISUAL feet land at
## origin+9, matching the player (feet row 41 of a 64px frame) and the prop
## baselines — Y-sort compares origins, so a mismatched baseline let a chicken
## draw over the face of a player standing below it (round-3). The sprite
## offset is compensated at spawn, so nothing moves visually. Values measured
## from each sheet's idle-frame alpha bbox by tools/gen_prop_table.py-style
## scanning: foot = sprite_offset.y - frame/2 + feet_row - 9.
const ANIMAL_ANIM := {
	"d":
	{
		"foot": -7.0,
		"idle": 0,
		"idle_n": 2,
		"walk": 1,
		"walk_n": 6,
		"wander": true,
		"radius": 18.0,
		"speed": 12.0
	},
	"U":
	{
		"foot": -7.0,
		"idle": 0,
		"idle_n": 2,
		"walk": 1,
		"walk_n": 6,
		"wander": true,
		"radius": 18.0,
		"speed": 12.0
	},
	"^":
	{
		"foot": -11.0,
		"idle": 0,
		"idle_n": 2,
		"walk": 1,
		"walk_n": 6,
		"wander": true,
		"radius": 16.0,
		"speed": 12.0
	},
	"h":
	{
		"foot": -4.0,
		"idle": 0,
		"idle_n": 2,
		"walk": 3,
		"walk_n": 6,
		"wander": true,
		"radius": 24.0,
		"speed": 16.0
	},
	"R":
	{
		"foot": -10.0,
		"idle": 0,
		"idle_n": 2,
		"walk": 1,
		"walk_n": 8,
		"wander": true,
		"radius": 16.0,
		"speed": 10.0
	},
	"j":
	{
		"foot": -10.0,
		"idle": 0,
		"idle_n": 2,
		"walk": 2,
		"walk_n": 10,
		"wander": true,
		"radius": 16.0,
		"speed": 14.0
	},
	"o": {"foot": -8.0, "idle": 0, "idle_n": 4},
	"p": {"foot": -11.0, "idle": 0, "idle_n": 4},
	"e": {"foot": -11.0, "idle": 0, "idle_n": 4},
	"C":
	{
		"foot": -11.0,
		"idle": 0,
		"idle_n": 2,
		"walk": 1,
		"walk_n": 2,
		"wander": true,
		"radius": 12.0,
		"speed": 8.0
	},
	"y":
	{
		"foot": -18.0,
		"frame_size": 8,
		"idle": 0,
		"idle_n": 2,
		"fly": true,
		"radius": 9.0,
		"period": 2.8,
		"idle_fps": 6.0
	},
	"a": {"foot": -6.0, "idle": 8, "idle_n": 4},
	"l": {"foot": -6.0, "idle": 8, "idle_n": 3},
	"k": {"foot": 5.0, "idle": 0, "idle_n": 9},
	"@": {"foot": 5.0, "idle": 0, "idle_n": 9},
}

var _def := LevelRegistry.get_def(Game.current_level_id)
var _map := LevelRegistry.make_map(Game.current_level_id)
var _rows := _map.rows()
var _tex_cache := {}

@onready var _world: Node2D = $World


func _ready() -> void:
	_check_symbol_coverage()
	_add_ground()
	# main._ready runs after $Level._ready (children-first), so build the
	# tilemap here with the active level's map — then hide it (collision-only;
	# the baked image carries the visuals).
	$Level.build(_map)
	$Level.modulate = Color(1.0, 1.0, 1.0, 0.0)
	var spawn := _map.cell_center(_entry_cell())
	$World/Player.position = spawn
	# 1P: drop the second player; the midpoint camera falls back to Player1.
	if Game.player_count >= 2:
		$World/Player2.position = spawn + Vector2(18, 0)
	else:
		$World/Player2.queue_free()
	# Shop + Ariana are valley-only; other levels drop them.
	if _def.has_shop:
		var stall := _map.cell_center(_map.find_one("H"))
		$World/Shop.position = stall
		# Evan himself, standing in front of his stand (modular boy sprite).
		var evan := EvanNpc.new()
		evan.position = stall + EVAN_OFFSET
		_world.add_child(evan)
	else:
		$World/Shop.queue_free()
	if _def.has_ariana:
		$World/Ariana.position = _map.cell_center(_map.find_one("$"))
		# The onboarding guide, standing near the village spawn (modular sprite).
		var guide := GuideNpc.new()
		guide.position = _map.cell_center(GUIDE_CELL)
		_world.add_child(guide)
	else:
		$World/Ariana.queue_free()
	_spawn_props()
	_spawn_fences()
	_spawn_transitions()
	_spawn_talkers()
	_spawn_chests()
	# Encounters/checkpoints/respawn — AFTER players are positioned so a
	# saved-checkpoint resume can override the default spawn.
	$World/EncounterManager.setup($HUD, _def.encounters, _map)
	_bind_hud()
	_maybe_play_intro()


## One Interactable per talkable map symbol: villagers "N", Ariana "$" (ids the
## story session fills in scripts/dialogue_data.gd), and the sealed library "L".
## The shared DialogueBox is instanced first so the talkers can find it by group.
func _spawn_talkers() -> void:
	var box := DIALOGUE_BOX_SCENE.instantiate()
	box.add_to_group("dialogue_box")
	add_child(box)
	for cell in _map.find_all("N"):
		_add_talker("villager_%d_%d" % [cell.x, cell.y], _map.cell_center(cell))
		# The body you walk up to: a modular villager whose look is unique per
		# cell (M10 — one premade sheet no longer plays every villager).
		var villager := VillagerNpc.new()
		villager.profile = VillagerNpc.profile_for(cell.x, cell.y)
		villager.position = _map.cell_center(cell)
		_world.add_child(villager)
	if _def.has_ariana:
		_add_talker("ariana", _map.cell_center(_map.find_one("$")))
		_add_talker("guide", _map.cell_center(GUIDE_CELL))
	for cell in _map.find_all("L"):
		_add_talker("library_door", _map.cell_center(cell))
	if _def.has_shop:
		_add_talker("evan", _map.cell_center(_map.find_one("H")) + EVAN_OFFSET)
	# Interior examine-triggers: baked "!" floor cells (bake_interior.py). The id
	# is derived from the level + cell, matching the villager_<x>_<y> convention,
	# so DialogueData coverage is CI-checkable. Only interiors carry "!".
	for cell in _map.find_all("!"):
		_add_talker(
			"note_%s_%d_%d" % [Game.current_level_id, cell.x, cell.y], _map.cell_center(cell)
		)


func _add_talker(npc_id: String, at: Vector2) -> void:
	var talker := Interactable.new()
	talker.npc_id = npc_id
	talker.position = at
	_world.add_child(talker)


## Reward chests, code-placed from LootData (the map's decorative `x` is a singleton
## and is suppressed in _spawn_props). Valley-only, like the guide/Ariana; runs after
## _spawn_talkers so the shared DialogueBox exists for the pickup message.
func _spawn_chests() -> void:
	if not _def.has_ariana:
		return
	for cell in LootData.CHESTS:
		var chest := Chest.new()
		chest.chest_id = LootData.chest_id(cell)
		chest.upgrade_id = LootData.CHESTS[cell]
		chest.position = _map.cell_center(cell)
		_world.add_child(chest)


## The cell the players spawn on: the named entry they arrived through (a door /
## map-edge crossing), else the map's own "S" spawn.
func _entry_cell() -> Vector2i:
	if _def.entries.has(Game.current_entry):
		return _def.entries[Game.current_entry]
	return _map.find_one("S")


## Play the intro cutscene once, only on a fresh New-Game valley start. main.tscn
## reloads on every door/Continue, so gate on the run flags: a door sets a
## non-empty current_entry, Continue sets resume_requested, and the one-shot
## intro_played blocks a second same-session New Game.
func _maybe_play_intro() -> void:
	if (
		Game.resume_requested
		or Game.current_entry != ""
		or Game.current_level_id != "valley"
		or Game.intro_played
	):
		return
	Game.intro_played = true
	$CutsceneDirector.play(_map.cell_center(Vector2i(162, 18)), $World/CameraTarget)


## Connect each live player's HP to its HUD bar. Player2 is freed in 1-player, so
## only bind it when it is really in play.
func _bind_hud() -> void:
	$HUD.bind_player($World/Player)
	if Game.player_count >= 2:
		$HUD.bind_player($World/Player2)


## Draw the baked ground composite behind the Y-sorted world.
func _add_ground() -> void:
	var ground := Sprite2D.new()
	ground.name = "Ground"
	ground.texture = load(_def.ground)
	ground.centered = false
	ground.z_index = -1
	add_child(ground)
	move_child(ground, 0)


func _texture(key: String) -> Texture2D:
	if not _tex_cache.has(key):
		_tex_cache[key] = load(PropTable.SHEETS[key])
	return _tex_cache[key]


func _symbol(x: int, y: int) -> String:
	if y < 0 or y >= _rows.size() or x < 0 or x >= _rows[y].length():
		return "~"
	return _rows[y][x]


## Every table-driven prop: a Y-sorted Sprite2D, wrapped in a StaticBody2D when
## it has a collider. Sprites are centred at the cell centre with the table's
## offset, so placement matches the preview exactly.
func _spawn_props() -> void:
	for y in _rows.size():
		var row := _rows[y]
		for x in row.length():
			var sym := row[x]
			if not PropTable.PROPS.has(sym):
				continue
			if sym == "x":
				continue  # chests are live Chest nodes now (see _spawn_chests)
			if sym == "N":
				continue  # villagers are modular VillagerNpc nodes now (_spawn_talkers)
			var spec: Array = PropTable.PROPS[sym]
			var base := _map.cell_center(Vector2i(x, y))
			if ANIMAL_ANIM.has(sym):
				_spawn_animal(sym, spec, base)
				continue
			var region: Rect2 = spec[1]
			var offset: Vector2 = spec[2]
			var collider: Vector2 = spec[3]
			var collider_offset: Vector2 = spec[4] if spec.size() > 4 else Vector2.ZERO
			var collision_segments: Array = spec[5] if spec.size() > 5 else []
			var sprite := Sprite2D.new()
			sprite.texture = _texture(spec[0])
			sprite.region_enabled = true
			sprite.region_rect = region
			sprite.offset = offset
			_style_prop(sprite, sym, spec[0], x, y)
			if collider == Vector2.ZERO and collision_segments.is_empty():
				sprite.position = base
				_world.add_child(sprite)
			else:
				var body := StaticBody2D.new()
				body.position = base
				body.add_child(sprite)
				if collider != Vector2.ZERO:
					_add_collision_shape(body, collider, collider_offset)
				for segment in collision_segments:
					_add_collision_shape(body, segment[0], segment[1])
				if sym == "z":
					body.add_child(_make_windmill_sails())
				_world.add_child(body)


## Per-cell cosmetic variation (map audit M10/M12), deterministic by cell so
## runs, saves, and the review composites always agree.
func _style_prop(sprite: Sprite2D, _sym: String, sheet_key: String, x: int, y: int) -> void:
	if sheet_key == "oak" or sheet_key == "oak_s":
		sprite.flip_h = (x * 31 + y * 17) % 2 == 1


## The windmill tower ships without its rotating cross (map audit M7 read it
## as "broken"); the pack keeps the animated sails in a separate 4-frame sheet
## mounted at the mast top.
func _make_windmill_sails() -> Sprite2D:
	var sails := Critter.new()
	sails.texture = load(WINDMILL_SAILS)
	sails.hframes = 4
	sails.position = Vector2(0, -64)
	sails.fps = 4.0
	sails.frame_count = 4
	sails.first_frame = 0
	return sails


func _add_collision_shape(body: StaticBody2D, size: Vector2, offset: Vector2) -> void:
	var shape := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = size
	shape.shape = rect
	shape.position = offset
	body.add_child(shape)


## Animals become a live AmbientAnimal (idle-bob + optional wander) instead of a
## static sprite. Uses the same sheet + foot offset as the prop table; hframes/
## vframes come from the sheet (all 32px frames). No collider — they're decor.
func _spawn_animal(sym: String, spec: Array, base: Vector2) -> void:
	var cfg: Dictionary = ANIMAL_ANIM[sym]
	var tex := _texture(spec[0])
	var animal := AmbientAnimal.new()
	animal.texture = tex
	var frame_size: float = cfg.get("frame_size", 32.0)
	animal.hframes = int(tex.get_width() / frame_size)
	animal.vframes = int(tex.get_height() / frame_size)
	# Sort-baseline fix: put the origin where the visual feet are (+9px, the
	# player/prop convention) and pull the sprite back so nothing moves.
	var foot: float = cfg.get("foot", 0.0)
	animal.offset = spec[2] - Vector2(0.0, foot)
	animal.position = base + Vector2(0.0, foot)
	animal.idle_row = cfg["idle"]
	animal.idle_count = cfg["idle_n"]
	animal.walk_row = cfg.get("walk", -1)
	animal.walk_count = cfg.get("walk_n", 6)
	animal.idle_fps = cfg.get("idle_fps", 2.0)
	animal.walk_fps = cfg.get("walk_fps", 6.0)
	animal.can_wander = cfg.get("wander", false)
	animal.wander_radius = cfg.get("radius", 16.0)
	animal.move_speed = cfg.get("speed", 10.0)
	animal.can_fly = cfg.get("fly", false)
	animal.flight_radius = cfg.get("radius", 8.0)
	animal.flight_period = cfg.get("period", 3.0)
	_world.add_child(animal)


## Fences need neighbour-aware pieces (a straight run vs a post), so they stay
## out of the flat prop table. F = wood pen fence (FREE Fences.png).
func _spawn_fences() -> void:
	var fences: Texture2D = _texture("fences") if PropTable.SHEETS.has("fences") else null
	if fences == null:
		fences = load("res://assets/cute_fantasy/Cute_Fantasy_Free/Outdoor decoration/Fences.png")
	for cell in _map.find_all("F"):
		var left := _symbol(cell.x - 1, cell.y) == "F"
		var right := _symbol(cell.x + 1, cell.y) == "F"
		var up := _symbol(cell.x, cell.y - 1) == "F"
		var down := _symbol(cell.x, cell.y + 1) == "F"
		var piece: Vector2i
		var col_size: Vector2
		if down and right and not left and not up:
			piece = Vector2i(1, 0)
			col_size = Vector2(12, 12)
		elif down and left and not right and not up:
			piece = Vector2i(3, 0)
			col_size = Vector2(12, 12)
		elif up and right and not left and not down:
			piece = Vector2i(1, 3)
			col_size = Vector2(12, 12)
		elif up and left and not right and not down:
			piece = Vector2i(3, 3)
			col_size = Vector2(12, 12)
		elif left or right:
			piece = (
				Vector2i(2, 0) if left and right else (Vector2i(1, 0) if right else Vector2i(3, 0))
			)
			col_size = Vector2(16, 6)
		elif up or down:
			piece = Vector2i(0, 1) if up and down else (Vector2i(0, 0) if down else Vector2i(0, 2))
			col_size = Vector2(6, 16)
		else:
			piece = Vector2i(0, 3)
			col_size = Vector2(6, 6)
		var region := Rect2(piece.x * 16, piece.y * 16, 16, 16)
		_add_solid(fences, region, Vector2.ZERO, cell, col_size)


## Build the level's edge/door travel volumes from registry data (cell rects),
## under World/Transitions. collision_mask 2 = the players physics layer, so a
## player body walking in triggers the crossing (and nothing else does).
func _spawn_transitions() -> void:
	var container := Node2D.new()
	container.name = "Transitions"
	_world.add_child(container)
	for t in _def.transitions:
		var rect: Rect2i = t.cells
		var origin := Vector2(rect.position) * MapData.TILE_SIZE
		var span := Vector2(rect.size) * MapData.TILE_SIZE
		var node := LevelTransition.new()
		node.target_level = t.to
		node.target_entry = t.entry
		node.position = origin + span / 2.0
		node.collision_layer = 0
		node.collision_mask = 2
		var shape := CollisionShape2D.new()
		var box := RectangleShape2D.new()
		box.size = span
		shape.shape = box
		node.add_child(shape)
		container.add_child(node)


func _add_solid(
	texture: Texture2D,
	region: Rect2,
	sprite_offset: Vector2,
	cell: Vector2i,
	collider_size: Vector2
) -> void:
	var body := StaticBody2D.new()
	body.position = _map.cell_center(cell)
	var sprite := Sprite2D.new()
	sprite.texture = texture
	sprite.region_enabled = true
	sprite.region_rect = region
	sprite.offset = sprite_offset
	body.add_child(sprite)
	var shape := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = collider_size
	shape.shape = rect
	body.add_child(shape)
	_world.add_child(body)


## Build-time guard: every unique symbol in the map must be handled by the prop
## table, the fence set, or the terrain set — never silently rendered as blank
## grass (the bug this whole slice fixes). Fails loud in the editor/run log.
func _check_symbol_coverage() -> void:
	var known := {}
	for s in PropTable.PROPS:
		known[s] = true
	for s in TERRAIN_SYMS:
		known[s] = true
	for s in FENCE_SYMS:
		known[s] = true
	var missing := {}
	for row in _rows:
		for i in row.length():
			var ch := row[i]
			if not known.has(ch):
				missing[ch] = true
	if not missing.is_empty():
		var chars := "".join(missing.keys())
		push_error(
			(
				"Level '%s': %d unhandled symbol(s) would render as blank grass: %s"
				% [Game.current_level_id, missing.size(), chars]
			)
		)
		assert(false, "Unhandled map symbols: " + chars)
