extends Node2D

## Scene orchestrator: draws the baked ground, then places every prop/entity
## from IslandMap as a live Y-sorted node (data in PropTable, generated by
## tools/gen_prop_table.py to mirror the preview renderer's pass 3).
##
## The below-player look (terrain + procedural detail + the stone-bridge floor)
## is a single pre-baked image (assets/generated/valley-1-ground.png). The Level
## TileMapLayer is kept ONLY for collision (water blocks; walkable tiles free)
## and rendered transparent — its visuals are superseded by the baked image.

const GROUND_IMAGE := "res://assets/generated/valley-1-ground.png"

## Symbols handled outside PropTable: terrain (painted + baked), fences (F needs
## neighbour-aware pieces), spawn. Used by the build-time coverage assert so a
## future map edit can never silently reintroduce the old blank-grass gap.
const TERRAIN_SYMS := [".", "#", "S", "~", "B", "D", "Q", "c", "g", "O", "k", "a", "l", "@"]
const FENCE_SYMS := ["F", "|"]

var _rows := IslandMap.rows()
var _tex_cache := {}

@onready var _world: Node2D = $World


func _ready() -> void:
	_check_symbol_coverage()
	_add_ground()
	# The tilemap is collision-only now; the baked image carries the visuals.
	$Level.modulate = Color(1.0, 1.0, 1.0, 0.0)
	var spawn := IslandMap.cell_center(IslandMap.find_one("S"))
	$World/Player.position = spawn
	$World/Player.respawn_point = spawn
	# 1P: drop the second player; the midpoint camera falls back to Player1.
	if Game.player_count >= 2:
		$World/Player2.position = spawn + Vector2(18, 0)
		$World/Player2.respawn_point = spawn + Vector2(18, 0)
	else:
		$World/Player2.queue_free()
	$World/Shop.position = IslandMap.cell_center(IslandMap.find_one("H"))
	$World/Ariana.position = IslandMap.cell_center(IslandMap.find_one("$"))
	_spawn_props()
	_spawn_fences()
	# Encounters/checkpoints/respawn — AFTER players are positioned so a
	# saved-checkpoint resume can override the default spawn.
	$World/EncounterManager.setup()


## Draw the baked ground composite behind the Y-sorted world.
func _add_ground() -> void:
	var ground := Sprite2D.new()
	ground.name = "Ground"
	ground.texture = load(GROUND_IMAGE)
	ground.centered = false
	ground.z_index = -1
	add_child(ground)
	move_child(ground, 0)


func _texture(key: String) -> Texture2D:
	if not _tex_cache.has(key):
		_tex_cache[key] = load(PropTable.SHEETS[key])
	return _tex_cache[key]


func _symbol(x: int, y: int) -> String:
	if y < 0 or y >= _rows.size() or x < 0 or x >= _rows[y].length():
		return "~"
	return _rows[y][x]


## Every table-driven prop: a Y-sorted Sprite2D, wrapped in a StaticBody2D when
## it has a collider. Sprites are centred at the cell centre with the table's
## offset, so placement matches the preview exactly.
func _spawn_props() -> void:
	for y in _rows.size():
		var row := _rows[y]
		for x in row.length():
			var sym := row[x]
			if not PropTable.PROPS.has(sym):
				continue
			var spec: Array = PropTable.PROPS[sym]
			var region: Rect2 = spec[1]
			var offset: Vector2 = spec[2]
			var collider: Vector2 = spec[3]
			var base := IslandMap.cell_center(Vector2i(x, y))
			var sprite := Sprite2D.new()
			sprite.texture = _texture(spec[0])
			sprite.region_enabled = true
			sprite.region_rect = region
			sprite.offset = offset
			if collider == Vector2.ZERO:
				sprite.position = base
				_world.add_child(sprite)
			else:
				var body := StaticBody2D.new()
				body.position = base
				body.add_child(sprite)
				var shape := CollisionShape2D.new()
				var rect := RectangleShape2D.new()
				rect.size = collider
				shape.shape = rect
				body.add_child(shape)
				_world.add_child(body)


## Fences need neighbour-aware pieces (a straight run vs a post), so they stay
## out of the flat prop table. F = wood pen fence (FREE Fences.png).
func _spawn_fences() -> void:
	var fences: Texture2D = _texture("fences") if PropTable.SHEETS.has("fences") else null
	if fences == null:
		fences = load("res://assets/cute_fantasy/Cute_Fantasy_Free/Outdoor decoration/Fences.png")
	for cell in IslandMap.find_all("F"):
		var left := _symbol(cell.x - 1, cell.y) == "F"
		var right := _symbol(cell.x + 1, cell.y) == "F"
		var up := _symbol(cell.x, cell.y - 1) == "F"
		var down := _symbol(cell.x, cell.y + 1) == "F"
		var piece: Vector2i
		var col_size: Vector2
		if down and right and not left and not up:
			piece = Vector2i(1, 0)
			col_size = Vector2(12, 12)
		elif down and left and not right and not up:
			piece = Vector2i(3, 0)
			col_size = Vector2(12, 12)
		elif up and right and not left and not down:
			piece = Vector2i(1, 3)
			col_size = Vector2(12, 12)
		elif up and left and not right and not down:
			piece = Vector2i(3, 3)
			col_size = Vector2(12, 12)
		elif left or right:
			piece = (
				Vector2i(2, 0) if left and right else (Vector2i(1, 0) if right else Vector2i(3, 0))
			)
			col_size = Vector2(16, 6)
		elif up or down:
			piece = Vector2i(0, 1) if up and down else (Vector2i(0, 0) if down else Vector2i(0, 2))
			col_size = Vector2(6, 16)
		else:
			piece = Vector2i(0, 3)
			col_size = Vector2(6, 6)
		var region := Rect2(piece.x * 16, piece.y * 16, 16, 16)
		_add_solid(fences, region, Vector2.ZERO, cell, col_size)


func _add_solid(
	texture: Texture2D,
	region: Rect2,
	sprite_offset: Vector2,
	cell: Vector2i,
	collider_size: Vector2
) -> void:
	var body := StaticBody2D.new()
	body.position = IslandMap.cell_center(cell)
	var sprite := Sprite2D.new()
	sprite.texture = texture
	sprite.region_enabled = true
	sprite.region_rect = region
	sprite.offset = sprite_offset
	body.add_child(sprite)
	var shape := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = collider_size
	shape.shape = rect
	body.add_child(shape)
	_world.add_child(body)


## Build-time guard: every unique symbol in the map must be handled by the prop
## table, the fence set, or the terrain set — never silently rendered as blank
## grass (the bug this whole slice fixes). Fails loud in the editor/run log.
func _check_symbol_coverage() -> void:
	var known := {}
	for s in PropTable.PROPS:
		known[s] = true
	for s in TERRAIN_SYMS:
		known[s] = true
	for s in FENCE_SYMS:
		known[s] = true
	var missing := {}
	for row in _rows:
		for i in row.length():
			var ch := row[i]
			if not known.has(ch):
				missing[ch] = true
	if not missing.is_empty():
		var chars := "".join(missing.keys())
		push_error(
			(
				"IslandMap: %d unhandled symbol(s) would render as blank grass: %s"
				% [missing.size(), chars]
			)
		)
		assert(false, "Unhandled map symbols: " + chars)
