class_name PropTable
extends RefCounted

## GENERATED by tools/gen_prop_table.py — do not edit by hand.
## Data table for main.gd: map symbol -> how to draw + collide a prop,
## mirroring tools/preview_map.py pass 3. Regenerate after sprite changes.

## sheet key -> preloaded texture path.
const SHEETS := {
	"apple_t": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Crops/Apple_Tree.png",
	"barn":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Unique_Buildings/Barn/Barn_Base_Red.png",
	"barrels":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/barrels.png",
	"beehive": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Bee/Bee_Hive.png",
	"bench":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Benches.png",
	"berries2": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Crops/Berries.png",
	"birch_b": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Trees/Big_Birch_Tree.png",
	"birch_s":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Trees/Small_Birch_Tree.png",
	"boat": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Boat.png",
	"bower": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Crops/Grapes_Bower.png",
	"butterfly":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Butterfly/Butterfly.png",
	"campdecor":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Camp_Decor.png",
	"campfire":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Outdoor_Decor_Animations/Other_Animations/Campfire_Anim.png",
	"capy":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Kapybara/Static/Kapybara_Idle.png",
	"capy2":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Kapybara/Static/Albino_Kapybara_Idle.png",
	"cherry_t": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Crops/Cherry_Tree.png",
	"chest": "res://assets/cute_fantasy/Cute_Fantasy_Free/Outdoor decoration/Chest.png",
	"chicken": "res://assets/cute_fantasy/Cute_Fantasy_Free/Animals/Chicken/Chicken.png",
	"cow": "res://assets/cute_fantasy/Cute_Fantasy_Free/Animals/Cow/Cow.png",
	"decor":
	"res://assets/cute_fantasy/Cute_Fantasy_Free/Outdoor decoration/Outdoor_Decor_Free.png",
	"duck": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Duck/Duck_01.png",
	"frog": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Frog/Frog_01.png",
	"goose": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Goose/Goose_01.png",
	"haybale":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Hay_Bales.png",
	"horse": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Horse/Horse_01.png",
	"house_a":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Houses/Wood/House_1_Wood_Base_Blue.png",
	"house_e":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Houses/Limestone/House_3_Limestone_Base_Red.png",
	"house_g":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Houses/Wood/House_2_Wood_Base_Red.png",
	"house_j":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Houses/Stone/House_4_Stone_Base_Blue.png",
	"inn":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Unique_Buildings/Inn/Inn_Black.png",
	"lamp2":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Lanter_Posts.png",
	"mouse": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Mouse/Mouse_01.png",
	"oak": "res://assets/cute_fantasy/Cute_Fantasy_Free/Outdoor decoration/Oak_Tree.png",
	"oak_s": "res://assets/cute_fantasy/Cute_Fantasy_Free/Outdoor decoration/Oak_Tree_Small.png",
	"pig": "res://assets/cute_fantasy/Cute_Fantasy_Free/Animals/Pig/Pig.png",
	"rooster":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Chicken/Rooster.png",
	"scarecrow":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Scarecrows.png",
	"sheep": "res://assets/cute_fantasy/Cute_Fantasy_Free/Animals/Sheep/Sheep.png",
	"spruce_b":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Trees/Big_Spruce_tree.png",
	"spruce_s":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Trees/Small_Spruce_Tree.png",
	"stall":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Unique_Buildings/Stalls/Market_Stalls.png",
	"swan": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Animals/Swan/Swan_01.png",
	"tent":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Tent/Tent_Small.png",
	"trough":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Water_Troughs.png",
	"villager":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/NPCs (Premade)/Farmer_Bob.png",
	"well": "res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/Well.png",
	"wfence":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Outdoor decoration/White_Fence.png",
	"windmill":
	"res://assets/cute_fantasy/packs/Cute_Fantasy/Cute_Fantasy/Buildings/Buildings/Unique_Buildings/Windmill/Windmill.png",
}

## symbol -> [sheet_key, region(x,y,w,h), sprite_offset(x,y), collider(w,h)]
## collider (0,0) = decor, no collision. Offset is from the cell centre.
const PROPS := {
	"$": ["duck", Rect2(0, 0, 32, 32), Vector2(0, -6), Vector2(0, 0)],
	"%": ["beehive", Rect2(0, 0, 16, 16), Vector2(0, -2), Vector2(10, 8)],
	"&": ["berries2", Rect2(0, 0, 16, 16), Vector2(0, 0), Vector2(0, 0)],
	"+": ["lamp2", Rect2(0, 0, 16, 48), Vector2(0, -16), Vector2(6, 8)],
	"0": ["campfire", Rect2(0, 0, 16, 32), Vector2(0, -8), Vector2(12, 10)],
	"1": ["campdecor", Rect2(0, 0, 16, 16), Vector2(0, 0), Vector2(0, 0)],
	"2": ["haybale", Rect2(0, 0, 16, 16), Vector2(0, 0), Vector2(12, 8)],
	"3": ["barrels", Rect2(0, 0, 16, 16), Vector2(0, -2), Vector2(10, 8)],
	"4": ["birch_s", Rect2(32, 0, 32, 64), Vector2(0, -24), Vector2(8, 6)],
	"5": ["birch_b", Rect2(32, 0, 32, 80), Vector2(0, -30), Vector2(12, 8)],
	"6": ["spruce_s", Rect2(32, 0, 32, 64), Vector2(0, -24), Vector2(8, 6)],
	"7": ["spruce_b", Rect2(64, 0, 64, 80), Vector2(0, -30), Vector2(12, 8)],
	"8": ["apple_t", Rect2(0, 0, 32, 64), Vector2(0, -24), Vector2(8, 6)],
	"9": ["cherry_t", Rect2(0, 0, 32, 64), Vector2(0, -24), Vector2(8, 6)],
	"=": ["trough", Rect2(16, 0, 32, 32), Vector2(0, -8), Vector2(28, 10)],
	"@": ["capy2", Rect2(0, 0, 32, 32), Vector2(0, -2), Vector2(0, 0)],
	"A": ["house_a", Rect2(0, 0, 96, 128), Vector2(0, -56), Vector2(52, 14)],
	"C": ["chicken", Rect2(0, 0, 32, 32), Vector2(0, -10), Vector2(0, 0)],
	"E": ["house_e", Rect2(0, 0, 144, 128), Vector2(0, -56), Vector2(52, 14)],
	"G": ["house_g", Rect2(0, 0, 144, 128), Vector2(0, -56), Vector2(52, 14)],
	"H": ["stall", Rect2(96, 0, 48, 48), Vector2(0, -16), Vector2(26, 10)],
	"J": ["house_j", Rect2(0, 0, 112, 96), Vector2(0, -40), Vector2(52, 14)],
	"K": ["scarecrow", Rect2(0, 0, 32, 32), Vector2(0, -8), Vector2(6, 10)],
	"L": ["inn", Rect2(0, 0, 240, 192), Vector2(0, -88), Vector2(90, 18)],
	"N": ["villager", Rect2(0, 0, 64, 64), Vector2(0, -22), Vector2(0, 0)],
	"O": ["boat", Rect2(0, 0, 48, 48), Vector2(0, -10), Vector2(0, 0)],
	"R": ["frog", Rect2(0, 0, 32, 32), Vector2(0, -6), Vector2(0, 0)],
	"T": ["oak", Rect2(0, 0, 64, 80), Vector2(0, -30), Vector2(12, 8)],
	"U": ["goose", Rect2(0, 0, 32, 32), Vector2(0, -6), Vector2(0, 0)],
	"W": ["well", Rect2(0, 0, 32, 48), Vector2(0, -18), Vector2(20, 12)],
	"Y": ["barn", Rect2(0, 0, 128, 144), Vector2(0, -64), Vector2(60, 16)],
	"^": ["rooster", Rect2(0, 0, 32, 32), Vector2(0, -10), Vector2(0, 0)],
	"a": ["duck", Rect2(0, 256, 32, 32), Vector2(0, -4), Vector2(0, 0)],
	"b": ["bench", Rect2(0, 0, 32, 32), Vector2(0, -2), Vector2(26, 8)],
	"d": ["duck", Rect2(0, 0, 32, 32), Vector2(0, -6), Vector2(0, 0)],
	"e": ["sheep", Rect2(0, 0, 32, 32), Vector2(0, -10), Vector2(0, 0)],
	"f": ["decor", Rect2(32, 176, 16, 16), Vector2(0, 0), Vector2(0, 0)],
	"g": ["bower", Rect2(96, 80, 96, 80), Vector2(0, -24), Vector2(0, 0)],
	"h": ["horse", Rect2(0, 0, 32, 32), Vector2(0, -10), Vector2(0, 0)],
	"i": ["decor", Rect2(64, 64, 16, 64), Vector2(0, -24), Vector2(6, 12)],
	"j": ["mouse", Rect2(0, 0, 32, 32), Vector2(0, -6), Vector2(0, 0)],
	"k": ["capy", Rect2(0, 0, 32, 32), Vector2(0, -2), Vector2(0, 0)],
	"l": ["swan", Rect2(0, 256, 32, 32), Vector2(0, -4), Vector2(0, 0)],
	"m": ["decor", Rect2(32, 112, 16, 16), Vector2(0, 0), Vector2(0, 0)],
	"n": ["decor", Rect2(48, 0, 16, 16), Vector2(0, 0), Vector2(8, 10)],
	"o": ["cow", Rect2(0, 0, 32, 32), Vector2(0, -10), Vector2(0, 0)],
	"p": ["pig", Rect2(0, 0, 32, 32), Vector2(0, -10), Vector2(0, 0)],
	"r": ["decor", Rect2(0, 48, 16, 16), Vector2(0, 0), Vector2(12, 8)],
	"s": ["tent", Rect2(0, 0, 48, 96), Vector2(0, -40), Vector2(26, 12)],
	"t": ["oak_s", Rect2(32, 0, 32, 48), Vector2(0, -16), Vector2(8, 6)],
	"u": ["decor", Rect2(0, 32, 16, 16), Vector2(0, 0), Vector2(10, 6)],
	"w": ["decor", Rect2(0, 16, 16, 16), Vector2(0, 0), Vector2(0, 0)],
	"x": ["chest", Rect2(0, 0, 16, 16), Vector2(0, -4), Vector2(12, 8)],
	"y": ["butterfly", Rect2(0, 0, 16, 16), Vector2(0, -12), Vector2(0, 0)],
	"z": ["windmill", Rect2(0, 0, 128, 112), Vector2(0, -48), Vector2(28, 14)],
	"|": ["wfence", Rect2(16, 0, 16, 16), Vector2(0, 0), Vector2(14, 6)],
}
